const items = [
  {
    id: 1,
    name: "Motor",
    desc: "An special motor designed for flights with small distance.",
    cost: 1500,
    img: "",
    count: 1,
  },
  {
    id: 2,
    name: "Motor MKII",
    desc: "Motor Mark II is designed for more distant routes.",
    cost: 3500,
    img: "",
    count: 1000,
  },
  {
    id: 3,
    name: "Electric circuit",
    desc: "Can handle basic operation, have 32gB memory.",
    cost: 3000,
    img: "",
    count: 1,
  },
  {
    id: 4,
    name: "Electric circuit MKII",
    desc: "Upgraded version of Electric circut, now it runs on 128bit.",
    cost: 9000,
    img: "",
    count: 1,
  },
  {
    id: 5,
    name: "Nozzles",
    desc: "Max speed is around 0.05c, carry weight about 2 tonne.",
    cost: 10000,
    img: "",
    count: 1,
  },
  {
    id: 6,
    name: "Nozzles MKII",
    desc: "Max speed is around 0.2c, carry weight about 10 tonne.",
    cost: 20000,
    img: "",
    count: 1,
  },
  {
    id: 7,
    name: "Nozzles MKIII",
    desc: "Max speed is around 0.3c, carry weight about 15 tonne.",
    cost: 30000,
    img: "",
    count: 1,
  },
  {
    id: 8,
    name: "Smal Chassis",
    desc: "You need to have it to build your own rocket.",
    cost: 50000,
    img: "",
    count: 1,
  },
  {
    id: 9,
    name: "Medium Chassis",
    desc: "Designed for better flight experience.",
    cost: 75000,
    img: "",
    count: 1,
  },
  {
    id: 10,
    name: "Big Chassis",
    desc: "Makes your rocket way too big.",
    cost: 100000,
    img: "",
    count: 1,
  },
  //   { id: 11, name: "", desc: "", cost: 0, img: "" },
  //   { id: 12, name: "", desc: "", cost: 0, img: "" },
  //   { id: 13, name: "", desc: "", cost: 0, img: "" },
  //   { id: 14, name: "", desc: "", cost: 0, img: "" },
  //   { id: 15, name: "", desc: "", cost: 0, img: "" },
  //   { id: 16, name: "", desc: "", cost: 0, img: "" },
  //   { id: 17, name: "", desc: "", cost: 0, img: "" },
  //   { id: 18, name: "", desc: "", cost: 0, img: "" },
  //   { id: 19, name: "", desc: "", cost: 0, img: "" },
  //   { id: 20, name: "", desc: "", cost: 0, img: "" },
  //   { id: 21, name: "", desc: "", cost: 0, img: "" },
  //   { id: 22, name: "", desc: "", cost: 0, img: "" },
  //   { id: 23, name: "", desc: "", cost: 0, img: "" },
  //   { id: 24, name: "", desc: "", cost: 0, img: "" },
];

export default items;
